
server:
  port: 9999

spring:
  data:
    mongodb:
      host: mongodb://localhost:27017
      database: auth-demo

jwt:
  secret:
    key: pFtzHkzwMZWguXpY9XfN0ikS0w7BVgDs7azZaRA+R3b4QWqIBdvkVNzoGSG5dJU/FJ3dIhttfunvh7IY3RhP/Q==

